### ISSUE TITLE
First time install + serve

### ISSUE THREAD

**Issue by VDABLaurensSegers** [Code-Pop/real-world-vue#44]
audited 856 packages in 2.821s

84 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\32479\Desktop\RWV\real-world-vue-master> npm run serve 

> real-world-vue@0.1.0 serve C:\Users\32479\Desktop\RWV\real-world-vue-master
> vue-cli-service serve

 ERROR  TypeError: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at module.exports (C:\Users\32479\Desktop\RWV\real-world-vue-master\node_modules\@vue\cli-plugin-eslint\index.js:21:27)
    at C:\Users\32479\Desktop\RWV\real-world-vue-master\node_modules\@vue\cli-service\lib\Service.js:82:9
    at Array.forEach (<anonymous>)
    at loadedCallback (C:\Users\32479\Desktop\RWV\real-world-vue-master\node_modules\@vue\cli-service\lib\Service.js:80:20)
    at Service.init (C:\Users\32479\Desktop\RWV\real-world-vue-master\node_modules\@vue\cli-service\lib\Service.js:97:14)
    at Service.run (C:\Users\32479\Desktop\RWV\real-world-vue-master\node_modules\@vue\cli-service\lib\Service.js:247:16)
    at Object.<anonymous> (C:\Users\32479\Desktop\RWV\real-world-vue-master\node_modules\@vue\cli-service\bin\vue-cli-service.js:37:9)    at Module._compile (internal/modules/cjs/loader.js:1085:14)    
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! real-world-vue@0.1.0 serve: `vue-cli-service serve`       
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the real-world-vue@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\32479\AppData\Roaming\npm-cache\_logs\2022-04-22T17_02_17_534Z-debug.log

**Comment by VDABLaurensSegers** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.1
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle real-world-vue@0.1.0~preserve: real-world-vue@0.1.0
6 info lifecycle real-world-vue@0.1.0~serve: real-world-vue@0.1.0
7 verbose lifecycle real-world-vue@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle real-world-vue@0.1.0~serve: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\32479\Desktop\RWV\real-world-vue-master\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\WinMerge;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\32479\AppData\Local\Microsoft\WindowsApps;;C:\Users\32479\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\32479\.dotnet\tools;C:\Users\32479\AppData\Roaming\npm
9 verbose lifecycle real-world-vue@0.1.0~serve: CWD: C:\Users\32479\Desktop\RWV\real-world-vue-master
10 silly lifecycle real-world-vue@0.1.0~serve: Args: [ '/d /s /c', 'vue-cli-service serve' ]
11 silly lifecycle real-world-vue@0.1.0~serve: Returned: code: 1  signal: null
12 info lifecycle real-world-vue@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: real-world-vue@0.1.0 serve: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid real-world-vue@0.1.0
15 verbose cwd C:\Users\32479\Desktop\RWV\real-world-vue-master
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
18 verbose node v14.17.1
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error real-world-vue@0.1.0 serve: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the real-world-vue@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
